GET http://localhost:3000/api/students

###

GET http://localhost:3000/api/students/2

###

POST http://localhost:3000/api/students
Content-Type: application/json

{
    "firstName": "Luke",
    "lastName": "Loecher" ,
    "classId": 2
}

###
DELETE http://localhost:3000/api/students/2

###

PATCH http://localhost:3000/api/students/3
Content-Type: application/json

{
    "firstName": "Joe",
    "lastName": "Loecher",
    "classId":2
}